version: '3.9'

services:

  postgres:
    container_name: clinica_puertas_jg_db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - clinica_puertas_jg_db_volume:/var/lib/postgresql/data/

volumes:
  clinica_puertas_jg_db_volume:
